force-app/main/default/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <description>This Object gives information about the error logs which have occured.</description>
    <label>Error Log</label>
    <nameField>
        <label>Error Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Error_Log__c/fields/Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Class_Name__c</fullName>
    <description>Desciribes the class name</description>
    <label>Class Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Current_User__c.field-meta.xml
<CustomField>
    <fullName>Current_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field will be a user lookup who generated the error.</description>
    <label>Current User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Error_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Error_Message__c</fullName>
    <description>This field captures the error message.</description>
    <label>Error Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Exception_Type__c.field-meta.xml
<CustomField>
    <fullName>Exception_Type__c</fullName>
    <description>This field will be used to store the exception type of the error.</description>
    <label>Exception Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Method_Name__c.field-meta.xml
<CustomField>
    <fullName>Method_Name__c</fullName>
    <description>Descrives the method name.</description>
    <label>Method Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Stack_Trace__c.field-meta.xml
<CustomField>
    <fullName>Stack_Trace__c</fullName>
    <description>This will be used to trace the stack of function calls, used for debugging.</description>
    <label>Stack Trace</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/classes/ECExceptionManager.cls
/**
 * @description       : 
 * @author            : Vamsi Mudaliar
 * @group             : 
 * @last modified on  : 02-15-2024
 * @last modified by  : Vamsi Mudaliar
**/
public with sharing class ECExceptionManager {
    
    public static void logException(String className, String methodName, Exception expRec){
        
        Error_Log__c exceptionRecord = new Error_Log__c();
        exceptionRecord.Method_Name__c = methodName;
        exceptionRecord.Class_Name__c = className;
        exceptionRecord.Exception_Type__c = expRec.getTypeName();
        exceptionRecord.Error_Message__c = expRec.getMessage();
        exceptionRecord.Stack_Trace__c = expRec.getStackTraceString();
        //Mapping Current User Details
        exceptionRecord.Current_User__c = UserInfo.getUserId();
        
        insert exceptionRecord;
    }
}