force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <description>This Custom Object is used to store Invoices.</description>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>This is a Lookup field used to store which particular order is this.</description>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Item__c/Invoice_Item__c.object-meta.xml
<CustomObject>
    <description>This field is used to track Invoice Item Details</description>
    <label>Invoice Item</label>
    <nameField>
        <displayFormat>INV-IT-{0000}</displayFormat>
        <label>Invoice Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Item__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <description>This field is used to track the parent Invoice. for this invoice item.</description>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Invoice Items</relationshipLabel>
    <relationshipName>Invoice_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used to track the product</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Invoice Items</relationshipLabel>
    <relationshipName>Invoice_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Item__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <description>Displays the quantiy of the product.</description>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ECGenerateInvoiceBatch.cls
/**
 * @description       : This Apex Class Generate Invoices for the Activated Orders Created Today.
 * @author            : Vamsi Mudaliar
 * @group             : 
 * @last modified on  : 02-15-2024
 * @last modified by  : Vamsi Mudaliar
**/
global with sharing class ECGenerateInvoiceBatch implements Database.Batchable<sObject> {
    
    private static String ACTIVATED = 'Activated';
    
    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator('SELECT Id, Name, OrderNumber, (SELECT Id,OrderId, Product2Id, Quantity, TotalPrice FROM OrderItems) FROM Order WHERE Status =\''+ ACTIVATED +'\' AND ActivatedDate = TODAY ');
    }
    
    global void execute(Database.BatchableContext bc, List<Order> ordersList) {
        try {
            // LOGIC FOR GENERATING INVOICES.
            List<Invoice__c> invoiceList = new List<Invoice__c>();
            List<Invoice_Item__c> invoiceItemList = new List<Invoice_Item__c>();
            List<OrderItem> orderItemList = new List<OrderItem>();
            Map<Id,Id> orderIdToInvoiceIdMap = new Map<Id,Id>();

            // Creating Invoices.
            for (Order activatedOrder : ordersList) {
                Invoice__c invoice = new Invoice__c(
                    Order__c = activatedOrder.Id
                    // Name = INVOICE_PREFIX + '-' + activatedOrder.OrderNumber
                );
                invoiceList.add(invoice);

                if(!activatedOrder.OrderItems.isEmpty()) {
                    orderItemList.addAll(activatedOrder.OrderItems);
                }
            }    
            if(!invoiceList.isEmpty()) {
                insert invoiceList;
            }
            // Creating InvoiceItems.
            for(Invoice__c invRec : [SELECT ID,Order__c FROM Invoice__c WHERE ID IN :invoiceList WITH SECURITY_ENFORCED]) {
                if(String.isNotBlank(invRec.Order__c)) {
                    orderIdToInvoiceIdMap.put(invRec.Order__c,invRec.Id);
                }
            } 

            for(OrderItem orderItemRec : orderItemList) {
                Invoice_Item__c invItemRec = new Invoice_Item__c(
                    Product__c = orderItemRec.Product2Id,
                    Quantity__c = orderItemRec.Quantity,
                    Price__c = orderItemRec.TotalPrice,
                    Invoice__c = orderIdToInvoiceIdMap.get(orderItemRec.OrderId)
                ); 
                invoiceItemList.add(invItemRec);
            }
            
            if(!invoiceItemList.isEmpty()) {
                insert invoiceItemList;
            }
        }
        catch(Exception ex) {
            ECExceptionManager.logException('ECGenerateInvoiceBatch', 'execute', ex);
        }
    }

    global void finish(Database.BatchableContext bc) {
        // Optionally, you can add any cleanup or logging logic here
    }
}