force-app/main/default/objects/Scheduler_Log__c/Scheduler_Log__c.object-meta.xml
<CustomObject>
    <description>This Custom Object will be used to track the last run data information about the schedule job.</description>
    <label>Scheduler Log</label>
    <nameField>
        <label>Scheduler Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scheduler Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Scheduler_Log__c/fields/Job_Name__c.field-meta.xml
<CustomField>
    <fullName>Job_Name__c</fullName>
    <description>This field represents the Job Name</description>
    <label>Job Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Scheduler_Log__c/fields/Last_Run__c.field-meta.xml
<CustomField>
    <fullName>Last_Run__c</fullName>
    <description>This field represents the time when the job was last run.</description>
    <label>Last Run</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/ECInvoiceGeneratorScheduler.cls
/**
 * @description       : This method will be used to schedule the Apex Job, and will run at midnight everyday.
 * @author            : Vamsi Mudaliar
 * @group             : 
 * @last modified on  : 02-14-2024
 * @last modified by  : Vamsi Mudaliar
**/
public with sharing class ECInvoiceGeneratorScheduler implements Schedulable {
    

    private static final String JOB_NAME = 'Invoice_Generation_Job';
    private static final String CRON_EXP = '0 0 0 * * ?'; // Run at midnight every day

    public void execute(SchedulableContext ctx) {
        Database.executeBatch(new ECGenerateInvoiceBatch());
        // Update Scheduler_Log__c record to update the LAST RUN.
        updateSchedulerLog();
    }

    // This method will be used to run the Scheduler.
    public static void scheduleInvoiceGeneration() {
        // Schedule the job
        System.schedule(JOB_NAME, CRON_EXP, new ECInvoiceGeneratorScheduler());
    }

    public static void updateSchedulerLog() {
        List<Scheduler_Log__c> logsToUpdate = [SELECT Id, Last_Run__c FROM Scheduler_Log__c WHERE Job_Name__c = :JOB_NAME LIMIT 1];

        if (!logsToUpdate.isEmpty()) {
            logsToUpdate[0].Last_Run__c = DateTime.now();
            update logsToUpdate;
        } else {
            Scheduler_Log__c newLog = new Scheduler_Log__c();
            newLog.Job_Name__c = JOB_NAME;
            newLog.Last_Run__c = DateTime.now();
            insert newLog;
        }
    }
}