force-app/main/default/objects/Scheduler_Log__c/Scheduler_Log__c.object-meta.xml
<CustomObject>
    <description>This Custom Object will be used to track the last run data information about the schedule job.</description>
    <label>Scheduler Log</label>
    <nameField>
        <label>Scheduler Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scheduler Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Scheduler_Log__c/fields/Last_Run__c.field-meta.xml
<CustomField>
    <fullName>Last_Run__c</fullName>
    <description>This field represents the time when the job was last run.</description>
    <label>Last Run</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/EC_ScheduleController.cls
/**
 * @description       : 
 * @author            : Vamsi Mudaliar
 * @group             : 
 * @last modified on  : 02-15-2024
 * @last modified by  : Vamsi Mudaliar
**/
public with sharing class EC_ScheduleController {
    
    private static final String JOB_NAME = 'Invoice_Generation_Job';

    public class ScheduledProcessWrapper {
        @AuraEnabled
        public Boolean isScheduled;
        @AuraEnabled 
        public String jobId;
        @AuraEnabled 
        public String lastRunInfo;
    }



    @AuraEnabled(cacheable=true)
    public static ScheduledProcessWrapper getScheduledProcessInfo() {
        try {
            ScheduledProcessWrapper res = new ScheduledProcessWrapper();

            List<CronTrigger> cronTriggerList = [SELECT Id,CronJobDetail.Name FROM CronTrigger WHERE CronJobDetail.Name =:JOB_NAME LIMIT 1];
            res.isScheduled = !cronTriggerList.isEmpty();
            if(!cronTriggerList.isEmpty()) {
               res.jobId =  cronTriggerList[0].Id;
            }
            // Query for Scheduler.
            List<Scheduler_Log__c> schedulerLogList = [SELECT ID,Last_Run__c FROM Scheduler_Log__c ORDER BY CreatedDate DESC LIMIT 1];
            if(!schedulerLogList.isEmpty()) {
                res.lastRunInfo = schedulerLogList[0].Last_Run__c?.format();
            }
            return res;
        }
        catch(Exception ex) {
            ECExceptionManager.logException('EC_ScheduleController', 'getScheduledProcessInfo', ex);
        }
        return null;
    }

    @AuraEnabled
    public static Boolean toggleScheduler() {
        try {
            List<CronTrigger> cronTriggerList = [SELECT Id,CronJobDetail.Name FROM CronTrigger WHERE CronJobDetail.Name =:JOB_NAME LIMIT 1];

            if(cronTriggerList.isEmpty()) {
                ECInvoiceGeneratorScheduler.scheduleInvoiceGeneration();
            } else {
                System.abortJob(cronTriggerList[0]?.Id);
            }
            return true;
        }
        catch(Exception ex) {
            ECExceptionManager.logException('EC_ScheduleController', 'getScheduledProcessInfo', ex);
        }
        return false;
    }

}